print("Hello world")
variable01 = input("What is your name? ")
print(f"Well, hello there {variable01}")
variable01 = input("What is your age? ")
type_of_variable = type(variable01)
print(f"Variable01 is of type {type_of_variable}")
# variable01 = int(variable01)
variable01 = float(variable01)
type_of_variable = type(variable01)
print(f"Variable01 is of type {type_of_variable}")
print(f"Your age is {variable01}")